### PR TITLE
2-feature-request-add-data-files

### LINKED ISSUE #2: [feature-request]: add data files
### What feature would you like to request?

Create a set of files using 1000 participants and upload a couple of them to the repo

### Optional: Suggest a solution

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by K-Beicher**
## Description

- This PR adds csv files to the data repo, this will aid with testing as you won't have to have Synthea installed on your local machine if you just need a couple of files.
- These changes are done to avoid forcing people to install Synthea in order to generate data that can be used for testing.

## Type of Review

- Needs a quick review

## Related Issues

Closes #2 [feature-request]: add data files

See also Issues #...

## Testing

- [ ] Yes
- [x] No, not needed (give a reason below)
- [ ] No, I need help writing them

These are static csv files, all we need is a place to store them.

## Reviewer Focus

Check that the files can be downloaded and still be read as csv files.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [x] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

### CODE REVIEW

**Review by philter87 — DISMISSED** [review]
I have approved, but I have a small note: Do we need the default PR template if we will usually just add csv files?

**Review by signekb — DISMISSED** [review]
👍

**Comment by K-Beicher** [comment]
> I have approved, but I have a small note: Do we need the default PR template if we will usually just add csv files?

There will be some documentation.  But you are right, I added it for my convenience, and to test that it also works if it is placed in the top folder :-)

**Comment by lwjohnst86** [comment]
GitHub by default obtains Pull request templates from the `.github` repo, so we don't need this file in this repo (at least at this point). If we implement the Issue https://github.com/seedcase-project/.github/issues/62 than it makes sense to have a dedicated on here. For now I will move it into the `.github` folder on this repo.

**Comment by lwjohnst86** [comment]
I've stripped out any really personal data, since we don't really need it nor is it something researchers encounter.

**Pull request merged**
